-- Rinlo Supabase foundation schema.
--
-- This is a reproducible baseline snapshot for the clean Rinlo Supabase project.
-- It intentionally uses Supabase Auth (auth.users) instead of the prototype's
-- app_users/auth_sessions tables. Convert this baseline to formal Supabase CLI
-- migrations with `supabase db pull` before a production migration workflow.

begin;

create extension if not exists pg_trgm with schema extensions;

-- Global, read-only food catalogue ------------------------------------------------

create table public.foods (
  id text primary key,
  name text not null,
  normalized_name text not null,
  kcal_100 numeric(8,2) not null check (kcal_100 >= 0),
  protein_100 numeric(8,2) not null default 0 check (protein_100 >= 0),
  fat_100 numeric(8,2),
  carbs_100 numeric(8,2),
  default_portion_g numeric(8,2) not null check (default_portion_g > 0),
  icon text,
  source text not null default 'healthy_action_seed',
  source_id text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.food_aliases (
  id bigint generated by default as identity primary key,
  food_id text not null references public.foods(id) on delete cascade,
  alias text not null,
  normalized_alias text not null,
  created_at timestamptz not null default now(),
  unique(food_id, normalized_alias)
);

create index foods_normalized_name_trgm_idx
  on public.foods using gin (normalized_name extensions.gin_trgm_ops);
create index food_aliases_normalized_alias_trgm_idx
  on public.food_aliases using gin (normalized_alias extensions.gin_trgm_ops);
create index food_aliases_food_id_idx on public.food_aliases(food_id);

-- User-owned data -----------------------------------------------------------------

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  sex text check (sex in ('male','female','other')),
  height_cm numeric(6,2) check (height_cm is null or height_cm between 100 and 250),
  start_weight_kg numeric(6,2) check (start_weight_kg is null or start_weight_kg between 30 and 300),
  target_weight_kg numeric(6,2) check (target_weight_kg is null or target_weight_kg between 30 and 300),
  age_years integer check (age_years is null or age_years between 14 and 100),
  activity text check (activity is null or activity in ('low','medium','high')),
  focuses text[] not null default '{}'::text[],
  primary_goal text check (
    primary_goal is null or primary_goal in ('weight_loss','nutrition','movement','sleep','energy','nicotine')
  ),
  secondary_goals text[] not null default '{}'::text[],
  calorie_tracking_enabled boolean not null default true,
  calorie_target integer,
  protein_target_g integer,
  step_target integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.food_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  eaten_at timestamptz not null default now(),
  source text not null default 'text' check (source in ('text','photo','voice','manual')),
  original_text text,
  total_kcal numeric(10,2) not null default 0 check (total_kcal >= 0),
  total_protein_g numeric(10,2) not null default 0 check (total_protein_g >= 0),
  client_event_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(id, user_id)
);

create unique index food_logs_user_client_event_id_uidx
  on public.food_logs(user_id, client_event_id)
  where client_event_id is not null;
create index food_logs_user_eaten_at_idx
  on public.food_logs(user_id, eaten_at desc);

create table public.food_log_items (
  id uuid primary key default gen_random_uuid(),
  food_log_id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  food_id text references public.foods(id),
  name text not null,
  grams numeric(8,2) not null check (grams > 0),
  kcal numeric(10,2) not null default 0 check (kcal >= 0),
  protein_g numeric(10,2) not null default 0 check (protein_g >= 0),
  confidence numeric(4,3) check (confidence is null or confidence between 0 and 1),
  created_at timestamptz not null default now(),
  constraint food_log_items_owner_fk foreign key (food_log_id, user_id)
    references public.food_logs(id, user_id) on delete cascade
);

create index food_log_items_log_id_idx on public.food_log_items(food_log_id);
create index food_log_items_user_id_idx on public.food_log_items(user_id);
create index food_log_items_food_id_idx on public.food_log_items(food_id);
create index food_log_items_log_owner_idx on public.food_log_items(food_log_id, user_id);

create table public.weight_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  measured_at timestamptz not null default now(),
  weight_kg numeric(6,2) not null check (weight_kg between 30 and 300),
  client_event_id text,
  created_at timestamptz not null default now()
);

create index weight_logs_user_measured_at_idx
  on public.weight_logs(user_id, measured_at desc);
create unique index weight_logs_user_client_event_id_uidx
  on public.weight_logs(user_id, client_event_id)
  where client_event_id is not null;

create table public.daily_metrics (
  user_id uuid not null references auth.users(id) on delete cascade,
  day date not null,
  water_ml integer not null default 0 check (water_ml >= 0),
  steps integer not null default 0 check (steps >= 0),
  habit_flags jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key(user_id, day)
);

create index daily_metrics_day_idx on public.daily_metrics(day);

create table public.daily_metric_operations (
  user_id uuid not null references auth.users(id) on delete cascade,
  operation_id text not null,
  day date not null,
  water_ml_delta integer not null default 0,
  steps_delta integer not null default 0,
  created_at timestamptz not null default now(),
  primary key(user_id, operation_id)
);

create index daily_metric_operations_day_idx
  on public.daily_metric_operations(user_id, day, created_at desc);

create table public.daily_checkins (
  user_id uuid not null references auth.users(id) on delete cascade,
  day date not null,
  wellbeing text not null check (wellbeing in ('poor','okay','good','great')),
  energy smallint check (energy is null or energy between 1 and 5),
  sleep_quality smallint check (sleep_quality is null or sleep_quality between 1 and 5),
  sleep_minutes integer check (sleep_minutes is null or sleep_minutes between 0 and 1440),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key(user_id, day)
);

create index daily_checkins_day_idx on public.daily_checkins(day);

create table public.rinlo_actions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  day date not null,
  kind text not null check (kind in ('movement','nutrition','recovery','hydration','sleep','nicotine','general')),
  title text not null,
  rationale text not null,
  effort_minutes integer check (effort_minutes is null or effort_minutes between 1 and 240),
  source text not null default 'rules' check (source in ('rules','ai','manual')),
  status text not null default 'suggested' check (status in ('suggested','accepted','completed','replaced','dismissed')),
  context jsonb not null default '{}'::jsonb,
  suggested_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(id, user_id)
);

create index rinlo_actions_user_day_idx
  on public.rinlo_actions(user_id, day, suggested_at desc);
create index rinlo_actions_user_status_idx
  on public.rinlo_actions(user_id, status, suggested_at desc);

create table public.rinlo_action_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  action_id uuid not null,
  event_type text not null check (event_type in ('shown','accepted','completed','replaced','dismissed','feedback')),
  reason_code text check (
    reason_code is null or reason_code in ('no_time','low_energy','inconvenient_now','dont_want','already_did_similar','other')
  ),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint rinlo_action_events_owner_fk foreign key (action_id, user_id)
    references public.rinlo_actions(id, user_id) on delete cascade
);

create index rinlo_action_events_action_idx
  on public.rinlo_action_events(action_id, created_at asc);
create index rinlo_action_events_user_idx
  on public.rinlo_action_events(user_id, created_at desc);
create index rinlo_action_events_action_owner_idx
  on public.rinlo_action_events(action_id, user_id);

-- Row-level security ---------------------------------------------------------------

alter table public.foods enable row level security;
alter table public.food_aliases enable row level security;
alter table public.profiles enable row level security;
alter table public.food_logs enable row level security;
alter table public.food_log_items enable row level security;
alter table public.weight_logs enable row level security;
alter table public.daily_metrics enable row level security;
alter table public.daily_metric_operations enable row level security;
alter table public.daily_checkins enable row level security;
alter table public.rinlo_actions enable row level security;
alter table public.rinlo_action_events enable row level security;

create policy "Authenticated users can read foods"
  on public.foods for select to authenticated using (true);
create policy "Authenticated users can read food aliases"
  on public.food_aliases for select to authenticated using (true);

create policy "Users manage own profile"
  on public.profiles for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users manage own food logs"
  on public.food_logs for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users manage own food log items"
  on public.food_log_items for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users manage own weight logs"
  on public.weight_logs for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users manage own daily metrics"
  on public.daily_metrics for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users manage own metric operations"
  on public.daily_metric_operations for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users manage own daily checkins"
  on public.daily_checkins for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users manage own Rinlo actions"
  on public.rinlo_actions for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users manage own Rinlo action events"
  on public.rinlo_action_events for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

-- Data API grants -----------------------------------------------------------------
-- New Supabase projects may not auto-expose new tables. Grants and RLS are
-- intentionally separate: grants make an operation reachable, RLS limits rows.

revoke all on table public.foods from anon, authenticated;
revoke all on table public.food_aliases from anon, authenticated;
revoke all on table public.profiles from anon, authenticated;
revoke all on table public.food_logs from anon, authenticated;
revoke all on table public.food_log_items from anon, authenticated;
revoke all on table public.weight_logs from anon, authenticated;
revoke all on table public.daily_metrics from anon, authenticated;
revoke all on table public.daily_metric_operations from anon, authenticated;
revoke all on table public.daily_checkins from anon, authenticated;
revoke all on table public.rinlo_actions from anon, authenticated;
revoke all on table public.rinlo_action_events from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

alter default privileges in schema public revoke all on tables from anon, authenticated;
alter default privileges in schema public revoke all on sequences from anon, authenticated;

grant select on table public.foods to authenticated;
grant select on table public.food_aliases to authenticated;
grant select, insert, update, delete on table public.profiles to authenticated;
grant select, insert, update, delete on table public.food_logs to authenticated;
grant select, insert, update, delete on table public.food_log_items to authenticated;
grant select, insert, update, delete on table public.weight_logs to authenticated;
grant select, insert, update, delete on table public.daily_metrics to authenticated;
grant select, insert, update, delete on table public.daily_metric_operations to authenticated;
grant select, insert, update, delete on table public.daily_checkins to authenticated;
grant select, insert, update, delete on table public.rinlo_actions to authenticated;
grant select, insert, update, delete on table public.rinlo_action_events to authenticated;

commit;
